Add Breadcrumbs to navigation
rekall-innovations/rekall-agent-server pull request #5
Opened 2017-11-03 19:21 UTC by kevthehermit

As the title says, adds hyperlink 

breadcrumbs for Client, Flows, Collections

![breadcrumbs](https://user-images.githubusercontent.com/2545096/32392108-29320fa6-c0cc-11e7-9190-901286a89ac0.png)

![breadcrumbs3](https://user-images.githubusercontent.com/2545096/32392120-2fb8f902-c0cc-11e7-9acf-347ec937b982.png)

2017-11-03 19:34 UTC, scudette requested changes

2017-11-03 19:34 UTC, scudette commented on applications/Rekall/static/js/rekall.js
> +        }) + "&" + $.param({client_id: client_id}) + "&" + $.param({flow_id: flow_id}),
I think you can just add these to the param() call above.

2017-11-03 19:34 UTC, scudette commented on applications/Rekall/views/flows/collection_view.html
> +      <li class="breadcrumb-item"><a href="{{=URL(c='flows', f='description')}}?client_id={{=client_id}}&flow_id={{=flow_id}}">{{=flow_id}}</a></li>
You can add these parameters to the var keyword arg of the URL() function:
http://www.web2pyref.com/reference/url-web2py-function

2017-11-03 19:36 UTC, kevthehermit commented
I'm used to Django :) will read the spec and update.

2017-11-03 19:53 UTC, scudette commented
This is a cool addition which makes navigation much better! Thanks :-).

The only minor thing is to use the provided functions which do the proper escaping. Using URL() and params() functions escapes parameters according to URL rules (not HTML escaping which is different). So it is always better to let these utility functions construct the URLs.

2017-11-04 17:16 UTC, scudette approved these changes

2017-11-04 17:16 UTC, merged